from app.models import db, environment, SCHEMA, Product, User
from sqlalchemy.sql import text


# Adds a product, you can add other products here if you want
def seed_products(users):
    products = [
        {
            "id": 1,
            "item_name": "Minh's Gundam Mech PC",
            "price": 59999.99,
            "category": "Computer",
            "description": "This is a super PC",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61NlvtrzMVL._AC_SX679_.jpg",
            "sellerId": 5,
        },
        {
            "id": 2,
            "item_name": "Jenny's Magical Mac",
            "price": 0.99,
            "category": "Computer",
            "description": "This is powered by a potato, but supercharged if Jenny uses it to DJ",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/81yOTN1RvhL._AC_SX679_.jpg",
            "sellerId": 6,
        },
        {
            "id": 3,
            "item_name": "Chris' One Piece Sound Package",
            "price": 299.99,
            "category": "Computer",
            "description": "This is a one of a life time deal",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/71mj5kFT5IL._AC_SX679_.jpg",
            "sellerId": 4,
        },
        {
            "id": 4,
            "item_name": "Thandi's Dragon Ball Rage",
            "price": 4.99,
            "category": "Computer",
            "description": "This is a super PC keyboard",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51qHaEKTgxL._AC_SX679_.jpg",
            "sellerId": 7,
        },
        {
            "id": 5,
            "item_name": "Luffy's Straw Hat Laptop",
            "price": 32.03,
            "category": "Computer",
            "description": "High-performance laptop with advanced features",
            "quantity": 10,
            "preview_imageURL": "https://m.media-amazon.com/images/I/611J00Y94JL._AC_SX679_.jpg",
            "sellerId": 1,
        },
        {
            "id": 6,
            "item_name": "Luffy's Pirate Jacket",
            "price": 482.40,
            "category": "Clothing",
            "description": "Warm and stylish jacket for winter",
            "quantity": 20,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51jR3ysBmfL._AC_UX679_.jpg",
            "sellerId": 1,
        },
        {
            "id": 7,
            "item_name": "Sailor Moon Hat",
            "price": 53.23,
            "category": "Clothing",
            "description": "Fashionable hat for all seasons",
            "quantity": 30,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61WGYMalsqL._AC_UX679_.jpg",
            "sellerId": 1,
        },
        {
            "id": 8,
            "item_name": "Naruto's Hokage Sweater",
            "price": 38.47,
            "category": "Clothing",
            "description": "Cozy sweater for chilly days",
            "quantity": 25,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61lDNn8cZiL._AC_UX679_.jpg",
            "sellerId": 1,
        },
        {
            "id": 9,
            "item_name": "My Hero Academia Socks",
            "price": 22.29,
            "category": "Clothing",
            "description": "Comfortable socks for everyday wear",
            "quantity": 50,
            "preview_imageURL": "https://m.media-amazon.com/images/I/81tHWmiJ11L._AC_UX679_.jpg",
            "sellerId": 1,
        },
        {
            "id": 10,
            "item_name": "Dragon Ball Z Shirt",
            "price": 103.54,
            "category": "Clothing",
            "description": "Versatile shirt for any occasion",
            "quantity": 35,
            "preview_imageURL": "https://m.media-amazon.com/images/I/71rE-2t6+YL._AC_UX679_.jpg",
            "sellerId": 1,
        },
        {
            "id": 11,
            "item_name": "Studio Ghibli Wall Art",
            "price": 234.32,
            "category": "Home Decor",
            "description": "Beautiful wall art inspired by Studio Ghibli films",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/81K61qIYsAL._AC_SX679_.jpg",
            "sellerId": 5,
        },
        {
            "id": 12,
            "item_name": "Sailor Moon Cushion",
            "price": 938.23,
            "category": "Home Decor",
            "description": "Elegant cushion featuring Sailor Moon design",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61EQfEsXmSL._AC_SX679_.jpg",
            "sellerId": 5,
        },
        {
            "id": 13,
            "item_name": "Naruto LED Lamp",
            "price": 112.39,
            "category": "Home Decor",
            "description": "Illuminate your room with a Naruto-inspired LED lamp",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51Qyj4sd12S._AC_.jpg",
            "sellerId": 5,
        },
        {
            "id": 14,
            "item_name": "Dragon Ball Z Coasters",
            "price": 523.93,
            "category": "Home Decor",
            "description": "Protect your furniture with Dragon Ball Z-themed coasters",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/611HU0kfxqL._AC_SX679_.jpg",
            "sellerId": 5,
        },
        {
            "id": 15,
            "item_name": "My Hero Academia Clock",
            "price": 102.49,
            "category": "Home Decor",
            "description": "Stay punctual with a My Hero Academia-themed clock",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/81NlyjjMRLL._AC_SX679_.jpg",
            "sellerId": 5,
        },
        {
            "id": 16,
            "item_name": "Sword Art Online Necklace",
            "price": 934.54,
            "category": "Accessories",
            "description": "Elegant necklace inspired by Sword Art Online",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/41nb4H0A7fL._AC_UX679_.jpg",
            "sellerId": 6,
        },
        {
            "id": 17,
            "item_name": "Attack on Titan Keychain",
            "price": 235.38,
            "category": "Accessories",
            "description": "Carry your keys with an Attack on Titan-themed keychain",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51ZJ4+NwIGL._AC_UX679_.jpg",
            "sellerId": 6,
        },
        {
            "id": 18,
            "item_name": "Tokyo Ghoul Ring",
            "price": 293.45,
            "category": "Accessories",
            "description": "Unique ring inspired by Tokyo Ghoul",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51eCWGqpQYL._AC_UX679_.jpg",
            "sellerId": 6,
        },
        {
            "id": 19,
            "item_name": "One Piece Bracelet",
            "price": 309.48,
            "category": "Accessories",
            "description": "Stylish bracelet inspired by One Piece",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61MN4iEseqL._AC_UY695_.jpg",
            "sellerId": 6,
        },
        {
            "id": 20,
            "item_name": "Naruto Headband",
            "price": 382.93,
            "category": "Accessories",
            "description": "Wear a Naruto headband and embrace the shinobi spirit",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61R3oVrvrcS._AC_UX679_.jpg",
            "sellerId": 6,
        },
        {
            "id": 21,
            "item_name": "Rem Waifu Body Pillow",
            "price": 381.84,
            "category": "Waifu Body Pillows",
            "description": "Cuddle with Rem from Re:Zero on this cozy body pillow",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61g25MIbQsL._AC_SL1080_.jpg",
            "sellerId": 7,
        },
        {
            "id": 22,
            "item_name": "Zero Two Waifu Body Pillow",
            "price": 65.37,
            "category": "Waifu Body Pillows",
            "description": "Embrace the beauty of Zero Two with this body pillow",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61dgyrqT+ZL._AC_SL1080_.jpg",
            "sellerId": 7,
        },
        {
            "id": 23,
            "item_name": "Nezuko Waifu Body Pillow",
            "price": 12.90,
            "category": "Waifu Body Pillows",
            "description": "Hug Nezuko from Demon Slayer with this adorable body pillow",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61q3hHN+mhL._AC_SL1500_.jpg",
            "sellerId": 7,
        },
        {
            "id": 24,
            "item_name": "Asuna Waifu Body Pillow",
            "price": 744.32,
            "category": "Waifu Body Pillows",
            "description": "Relax with Asuna from Sword Art Online on this premium body pillow",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61gp1pOTWnL._AC_SL1080_.jpg",
            "sellerId": 7,
        },
        {
            "id": 25,
            "item_name": "Mikasa Waifu Body Pillow",
            "price": 28.40,
            "category": "Waifu Body Pillows",
            "description": "Feel protected with Mikasa from Attack on Titan on this body pillow",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61cvMMHYBCS._AC_SL1500_.jpg",
            "sellerId": 7,
        },
        {
            "id": 26,
            "item_name": "Naruto Manga Volume 1",
            "price": 123.94,
            "category": "Books",
            "description": "The first volume of the legendary Naruto manga series",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51VfPmZt5yL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg",
            "sellerId": 1,
        },
        {
            "id": 27,
            "item_name": "Attack on Titan Manga Volume 1",
            "price": 887.46,
            "category": "Books",
            "description": "The gripping first volume of Attack on Titan manga",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51QWSFImgvL._SY346_.jpg",
            "sellerId": 1,
        },
        {
            "id": 28,
            "item_name": "One Piece Manga Volume 1-2-3",
            "price": 24.99,
            "category": "Books",
            "description": "Embark on the adventures with One Piece manga volume 1-2-3",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51xr8s57oVL._SX328_BO1,204,203,200_.jpg",
            "sellerId": 1,
        },
        {
            "id": 29,
            "item_name": "My Hero Academia Manga Volume 1",
            "price": 19.99,
            "category": "Books",
            "description": "Begin the journey of heroes with My Hero Academia manga volume 1",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51cfpB+DHAL._SY344_BO1,204,203,200_.jpg",
            "sellerId": 1,
        },
        {
            "id": 30,
            "item_name": "Tokyo Ghoul Manga Volume 1",
            "price": 15.49,
            "category": "Books",
            "description": "Experience the world of ghouls with Tokyo Ghoul manga volume 1",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51uWQfEYayL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg"
        },
        {
            "id": 31,
            "item_name": "Studio Ghibli Soundtrack CD",
            "price": 19.99,
            "category": "Music",
            "description": "Enjoy the melodies of your favorite anime with this soundtrack CD",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51rVr8dkd9L._SX466_.jpg",
            "sellerId": 5,
        },
        {
            "id": 32,
            "item_name": "Naruto Soundtrack CD",
            "price": 12.49,
            "category": "Music",
            "description": "Get into the groove with this popular Naruto album",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61uHIR22d9L.jpg",
            "sellerId": 5,
        },
        {
            "id": 33,
            "item_name": "One Piece Single",
            "price": 9.99,
            "category": "Music",
            "description": "Relive the excitement of One Piece opening theme with this single",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61MWPBnC0sL.jpg",
            "sellerId": 5,
        },
        {
            "id": 34,
            "item_name": "Anime Ending Theme Single",
            "price": 9.99,
            "category": "Music",
            "description": "Experience the emotion of the anime's ending theme with this single",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61GU+U+qtTS._SX522_.jpg",
            "sellerId": 5,
        },
        {
            "id": 35,
            "item_name": "YuYu Hakusho Song Album",
            "price": 14.99,
            "category": "Music",
            "description": "Listen to the character songs of your beloved anime characters with this album",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61DPw6m+GLL._SX466_.jpg",
            "sellerId": 5,
        },
        {
            "id": 36,
            "item_name": "Naruto Uzumaki Figurine",
            "price": 34.99,
            "category": "Figurines",
            "description": "Bring the hero of the Hidden Leaf Village to your collection",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61z1RE3Q2OL._AC_SX679_.jpg",
            "sellerId": 6,
        },
        {
            "id": 37,
            "item_name": "Sailor Moon Figurine",
            "price": 29.99,
            "category": "Figurines",
            "description": "Capture the elegance of Sailor Moon in this exquisite figurine",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61T8YWPpQaL._AC_SX679_.jpg",
            "sellerId": 6,
        },
        {
            "id": 38,
            "item_name": "Dragon Ball Z Goku Figurine",
            "price": 39.99,
            "category": "Figurines",
            "description": "Power up your collection with the iconic Goku figurine",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/71c-lQzlcDL._AC_SY879_.jpg",
            "sellerId": 6,
        },
        {
            "id": 39,
            "item_name": "My Hero Academia Deku Figurine",
            "price": 26.99,
            "category": "Figurines",
            "description": "Embrace the spirit of heroism with this Deku figurine",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61C84cRTjTL._AC_SX679_.jpg",
            "sellerId": 6,
        },
        {
            "id": 40,
            "item_name": "Attack on Titan Levi Figurine",
            "price": 42.99,
            "category": "Figurines",
            "description": "Display the strength and determination of Levi in this figurine",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/6168e+KeTFL._AC_SY879_.jpg",
            "sellerId": 6,
        },
    ]

    for product in products:
        each_product = Product(**product)
        print(each_product)
        db.session.add(each_product)
        db.session.commit()
    return products


# Uses a raw SQL query to TRUNCATE or DELETE the products table. SQLAlchemy doesn't
# have a built in function to do this. With postgres in production TRUNCATE
# removes all the data from the table, and RESET IDENTITY resets the auto
# incrementing primary key, CASCADE deletes any dependent entities.  With
# sqlite3 in development you need to instead use DELETE to remove all data and
# it will reset the primary keys for you as well.
def undo_products():
    if environment == "production":
        db.session.execute(
            f"TRUNCATE table {SCHEMA}.products RESTART IDENTITY CASCADE;"
        )
    else:
        db.session.execute(text("DELETE FROM products"))

    db.session.commit()
