from app.models import db, environment, SCHEMA, Product, User
from sqlalchemy.sql import text


# Adds a product, you can add other products here if you want
def seed_products(users):
    products = [
        {
            "id": 1,
            "item_name": "Minh's Gundam Mech PC",
            "price": 59999.99,
            "category": "Computer",
            "description": "This is a super PC",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61NlvtrzMVL._AC_SX679_.jpg",
            "sellerId": 5,
        },
        {
            "id": 2,
            "item_name": "Jenny's Magical Mac",
            "price": 0.99,
            "category": "Computer",
            "description": "This is powered by a potato, but supercharged if Jenny uses it to DJ",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/81yOTN1RvhL._AC_SX679_.jpg",
            "sellerId": 6,
        },
        {
            "id": 3,
            "item_name": "Chris' One Piece Sound Package",
            "price": 299.99,
            "category": "Computer",
            "description": "This is a one of a life time deal",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/71mj5kFT5IL._AC_SX679_.jpg",
            "sellerId": 4,
        },
        {
            "id": 4,
            "item_name": "Thandi's Dragon Ball Rage",
            "price": 4.99,
            "category": "Computer",
            "description": "This is a super PC keyboard",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51qHaEKTgxL._AC_SX679_.jpg",
            "sellerId": 7,
        },
        {
            "id": 5,
            "item_name": "Luffy's Straw Hat Laptop",
            "price": 32.03,
            "category": "Computer",
            "description": "High-performance laptop with advanced features",
            "quantity": 10,
            "preview_imageURL": "https://m.media-amazon.com/images/I/611J00Y94JL._AC_SX679_.jpg",
            "sellerId": 1,
        },
        {
            "id": 6,
            "item_name": "Luffy's Pirate Jacket",
            "price": 482.40,
            "category": "Clothing",
            "description": "Warm and stylish jacket for winter",
            "quantity": 20,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51jR3ysBmfL._AC_UX679_.jpg",
            "sellerId": 1,
        },
        {
            "id": 7,
            "item_name": "Sailor Moon Hat",
            "price": 53.23,
            "category": "Clothing",
            "description": "Fashionable hat for all seasons",
            "quantity": 30,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61WGYMalsqL._AC_UX679_.jpg",
            "sellerId": 1,
        },
        {
            "id": 8,
            "item_name": "Naruto's Hokage Sweater",
            "price": 38.47,
            "category": "Clothing",
            "description": "Cozy sweater for chilly days",
            "quantity": 25,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61lDNn8cZiL._AC_UX679_.jpg",
            "sellerId": 1,
        },
        {
            "id": 9,
            "item_name": "My Hero Academia Socks",
            "price": 22.29,
            "category": "Clothing",
            "description": "Comfortable socks for everyday wear",
            "quantity": 50,
            "preview_imageURL": "https://m.media-amazon.com/images/I/81tHWmiJ11L._AC_UX679_.jpg",
            "sellerId": 1,
        },
        {
            "id": 10,
            "item_name": "Dragon Ball Z Shirt",
            "price": 103.54,
            "category": "Clothing",
            "description": "Versatile shirt for any occasion",
            "quantity": 35,
            "preview_imageURL": "https://m.media-amazon.com/images/I/71rE-2t6+YL._AC_UX679_.jpg",
            "sellerId": 1,
        },
        {
            "id": 11,
            "item_name": "Studio Ghibli Wall Art",
            "price": 234.32,
            "category": "Home Decor",
            "description": "Beautiful wall art inspired by Studio Ghibli films",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/81K61qIYsAL._AC_SX679_.jpg",
            "sellerId": 5,
        },
        {
            "id": 12,
            "item_name": "Sailor Moon Cushion",
            "price": 938.23,
            "category": "Home Decor",
            "description": "Elegant cushion featuring Sailor Moon design",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61EQfEsXmSL._AC_SX679_.jpg",
            "sellerId": 5,
        },
        {
            "id": 13,
            "item_name": "Naruto LED Lamp",
            "price": 112.39,
            "category": "Home Decor",
            "description": "Illuminate your room with a Naruto-inspired LED lamp",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51Qyj4sd12S._AC_.jpg",
            "sellerId": 5,
        },
        {
            "id": 14,
            "item_name": "Dragon Ball Z Coasters",
            "price": 523.93,
            "category": "Home Decor",
            "description": "Protect your furniture with Dragon Ball Z-themed coasters",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/611HU0kfxqL._AC_SX679_.jpg",
            "sellerId": 5,
        },
        {
            "id": 15,
            "item_name": "My Hero Academia Clock",
            "price": 102.49,
            "category": "Home Decor",
            "description": "Stay punctual with a My Hero Academia-themed clock",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/81NlyjjMRLL._AC_SX679_.jpg",
            "sellerId": 5,
        },
        {
            "id": 16,
            "item_name": "Sword Art Online Necklace",
            "price": 934.54,
            "category": "Accessories",
            "description": "Elegant necklace inspired by Sword Art Online",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/41nb4H0A7fL._AC_UX679_.jpg",
            "sellerId": 6,
        },
        {
            "id": 17,
            "item_name": "Attack on Titan Keychain",
            "price": 235.38,
            "category": "Accessories",
            "description": "Carry your keys with an Attack on Titan-themed keychain",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51ZJ4+NwIGL._AC_UX679_.jpg",
            "sellerId": 6,
        },
        {
            "id": 18,
            "item_name": "Tokyo Ghoul Ring",
            "price": 293.45,
            "category": "Accessories",
            "description": "Unique ring inspired by Tokyo Ghoul",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51eCWGqpQYL._AC_UX679_.jpg",
            "sellerId": 6,
        },
        {
            "id": 19,
            "item_name": "One Piece Bracelet",
            "price": 309.48,
            "category": "Accessories",
            "description": "Stylish bracelet inspired by One Piece",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61MN4iEseqL._AC_UY695_.jpg",
            "sellerId": 6,
        },
        {
            "id": 20,
            "item_name": "Naruto Headband",
            "price": 382.93,
            "category": "Accessories",
            "description": "Wear a Naruto headband and embrace the shinobi spirit",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61R3oVrvrcS._AC_UX679_.jpg",
            "sellerId": 6,
        },
        {
            "id": 21,
            "item_name": "Rem Waifu Body Pillow",
            "price": 381.84,
            "category": "Waifu Body Pillows",
            "description": "Cuddle with Rem from Re:Zero on this cozy body pillow",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61g25MIbQsL._AC_SL1080_.jpg",
            "sellerId": 5,
        },
        {
            "id": 22,
            "item_name": "Zero Two Waifu Body Pillow",
            "price": 65.37,
            "category": "Waifu Body Pillows",
            "description": "Embrace the beauty of Zero Two with this body pillow",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61dgyrqT+ZL._AC_SL1080_.jpg",
            "sellerId": 5,
        },
        {
            "id": 23,
            "item_name": "Nezuko Waifu Body Pillow",
            "price": 12.90,
            "category": "Waifu Body Pillows",
            "description": "Hug Nezuko from Demon Slayer with this adorable body pillow",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61q3hHN+mhL._AC_SL1500_.jpg",
            "sellerId": 5,
        },
        {
            "id": 24,
            "item_name": "Asuna Waifu Body Pillow",
            "price": 744.32,
            "category": "Waifu Body Pillows",
            "description": "Relax with Asuna from Sword Art Online on this premium body pillow",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61gp1pOTWnL._AC_SL1080_.jpg",
            "sellerId": 5,
        },
        {
            "id": 25,
            "item_name": "Mikasa Waifu Body Pillow",
            "price": 28.40,
            "category": "Waifu Body Pillows",
            "description": "Feel protected with Mikasa from Attack on Titan on this body pillow",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61cvMMHYBCS._AC_SL1500_.jpg",
            "sellerId": 5,
        },
        {
            "id": 26,
            "item_name": "Naruto Manga Volume 1",
            "price": 123.94,
            "category": "Books",
            "description": "The first volume of the legendary Naruto manga series",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51VfPmZt5yL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg",
            "sellerId": 1,
        },
        {
            "id": 27,
            "item_name": "Attack on Titan Manga Volume 1",
            "price": 887.46,
            "category": "Books",
            "description": "The gripping first volume of Attack on Titan manga",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51QWSFImgvL._SY346_.jpg",
            "sellerId": 1,
        },
        {
            "id": 28,
            "item_name": "One Piece Manga Volume 1-2-3",
            "price": 24.99,
            "category": "Books",
            "description": "Embark on the adventures with One Piece manga volume 1-2-3",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51xr8s57oVL._SX328_BO1,204,203,200_.jpg",
            "sellerId": 1,
        },
        {
            "id": 29,
            "item_name": "My Hero Academia Manga Volume 1",
            "price": 19.99,
            "category": "Books",
            "description": "Begin the journey of heroes with My Hero Academia manga volume 1",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51cfpB+DHAL._SY344_BO1,204,203,200_.jpg",
            "sellerId": 1,
        },
        {
            "id": 30,
            "item_name": "Tokyo Ghoul Manga Volume 1",
            "price": 15.49,
            "category": "Books",
            "description": "Experience the world of ghouls with Tokyo Ghoul manga volume 1",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51uWQfEYayL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg",
            "sellerId": 1,
        },
        {
            "id": 31,
            "item_name": "Studio Ghibli Soundtrack CD",
            "price": 19.99,
            "category": "Music",
            "description": "Enjoy the melodies of your favorite anime with this soundtrack CD",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51rVr8dkd9L._SX466_.jpg",
            "sellerId": 5,
        },
        {
            "id": 32,
            "item_name": "Naruto Soundtrack CD",
            "price": 12.49,
            "category": "Music",
            "description": "Get into the groove with this popular Naruto album",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61uHIR22d9L.jpg",
            "sellerId": 5,
        },
        {
            "id": 33,
            "item_name": "One Piece Single",
            "price": 9.99,
            "category": "Music",
            "description": "Relive the excitement of One Piece opening theme with this single",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61MWPBnC0sL.jpg",
            "sellerId": 5,
        },
        {
            "id": 34,
            "item_name": "Anime Ending Theme Single",
            "price": 9.99,
            "category": "Music",
            "description": "Experience the emotion of the anime's ending theme with this single",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61GU+U+qtTS._SX522_.jpg",
            "sellerId": 5,
        },
        {
            "id": 35,
            "item_name": "YuYu Hakusho Song Album",
            "price": 14.99,
            "category": "Music",
            "description": "Listen to the character songs of your beloved anime characters with this album",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61DPw6m+GLL._SX466_.jpg",
            "sellerId": 5,
        },
        {
            "id": 36,
            "item_name": "Naruto Uzumaki Figurine",
            "price": 34.99,
            "category": "Figurines",
            "description": "Bring the hero of the Hidden Leaf Village to your collection",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61z1RE3Q2OL._AC_SX679_.jpg",
            "sellerId": 6,
        },
        {
            "id": 37,
            "item_name": "Sailor Moon Figurine",
            "price": 29.99,
            "category": "Figurines",
            "description": "Capture the elegance of Sailor Moon in this exquisite figurine",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61T8YWPpQaL._AC_SX679_.jpg",
            "sellerId": 6,
        },
        {
            "id": 38,
            "item_name": "Dragon Ball Z Goku Figurine",
            "price": 39.99,
            "category": "Figurines",
            "description": "Power up your collection with the iconic Goku figurine",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/71c-lQzlcDL._AC_SY879_.jpg",
            "sellerId": 6,
        },
        {
            "id": 39,
            "item_name": "My Hero Academia Deku Figurine",
            "price": 26.99,
            "category": "Figurines",
            "description": "Embrace the spirit of heroism with this Deku figurine",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61C84cRTjTL._AC_SX679_.jpg",
            "sellerId": 6,
        },
        {
            "id": 40,
            "item_name": "Attack on Titan Levi Figurine",
            "price": 42.99,
            "category": "Figurines",
            "description": "Display the strength and determination of Levi in this figurine",
            "quantity": 1,
            "preview_imageURL": "https://m.media-amazon.com/images/I/6168e+KeTFL._AC_SY879_.jpg",
            "sellerId": 6,
        },
         {
            "id": 41,
            "item_name": "Cool color changing headsets",
            "price": 19.99,
            "category": "Computer",
            "description": "Gaming Headset for PC with Mic PS4/PS5 Xbox One,ENVEL Over-Ear Headphones with Volume Control RGB LED Light Cool Stereo,Noise Reduction for Laptops,Smartphone,Computer",
            "quantity": 6,
            "preview_imageURL": "https://m.media-amazon.com/images/I/71ca3Dw2YvS.jpg",
            "sellerId": 7,
        },
          {
            "id": 42,
            "item_name": "Kawaii keyboard",
            "price": 29.99,
            "category": "Computer",
            "description": "SELORSS Kawaii Wireless Bluetooth Cute Cat Keyboard,Mini Portable 84Keys Retro Round Keycaps,Quiet Click for Typewriter,Home and Office,Compatible with PC/Mac/Notebook/Laptop/Ipad Air(Pink Colorful)",
            "quantity": 30,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61E9TUWewfL._AC_UF894,1000_QL80_.jpg",
            "sellerId": 7,
        },
         {
            "id": 43,
            "item_name": "Gaming mouse",
            "price": 50.99,
            "category": "Computer",
            "description": "Cool 4000 DPI Mice 6 LED Buttons Wired USB Optical Gaming Mouse For Pro Gamer_US",
            "quantity": 5,
            "preview_imageURL": "https://i.ebayimg.com/images/g/NFAAAOSwWSlbyuKE/s-l1600.jpg",
            "sellerId": 3,
        },
        {
            "id": 44,
            "item_name": "Kawaii Frog Mouse pad",
            "price": 16.08,
            "category": "Computer",
            "description": "Kawaii Frog Mouse pad - Cute Frog Mouse Mat - Cute Frog Illustrated Mousemat - Kawaii Mouse mat - Fall Decor - Office Decor",
            "quantity": 8,
            "preview_imageURL": "https://i.etsystatic.com/11663546/r/il/a16b27/2610455987/il_570xN.2610455987_ldki.jpg",
            "sellerId": 7,
        },
         {
            "id": 45,
            "item_name": "Cute Zero Two Anime",
            "price": 27.77,
            "category": "Computer",
            "description": "laptop skin",
            "quantity": 22,
            "preview_imageURL": "https://ih1.redbubble.net/image.950233661.7889/pd,x500,macbook_air_13-pad,750x1000,f8f8f8.jpg",
            "sellerId": 1,
        },
         {
            "id": 46,
            "item_name": "Black Cargo pants",
            "price": 15.99,
            "category": "Clothing",
            "description": "Own your inner darkness in these black baggy pants! Hot n' loaded with metal hardware, these stylish street goth pants feature silver O-rings, buckles, and zipper details. Complete with removable bondage straps and metal eyelets along the waistline. Adjust the accent straps around your legs for the sinfully perfect fit. Zip up the pant legs for a change in style!",
            "quantity": 43,
            "preview_imageURL": "https://i.pinimg.com/564x/1f/2f/17/1f2f173c65c43599390ce5ed5437386c.jpg",
            "sellerId": 1,
        },
         {
            "id": 47,
            "item_name": "EDGY MULTI POCKETS LOW WAIST GRAY PANTS",
            "price": 52.90,
            "category": "Clothing",
            "description": "Old school is back this season so what was popular during 2000’s makes a comeback to our wardrobes just like these Edgy Multi Pockets Low Waist Gray Pants! Combine them with sneakers and a crop top to be fashionable this fall!",
            "quantity": 20,
            "preview_imageURL": "https://cdn11.bigcommerce.com/s-c7qlm8a06j/images/stencil/1280x1280/products/2537/23832/product-image-1845446700__78603.1644014102.jpg?c=1?imbypass=on",
            "sellerId": 3,
        },
        {
            "id": 48,
            "item_name": "CHEAP GRUNGE T-SHIRT",
            "price": 6.97,
            "category": "Clothing",
            "description": "Gothic T-Shirt Skeleton Print Grunge Aesthetic Goth T Shirt Dark Edgy Fashion Streetwear Graphic Tee",
            "quantity": 25,
            "preview_imageURL": "https://img.joomcdn.net/358773d6ce397492a16a3d16ef817b780ff4936a_original.jpeg",
            "sellerId": 3,
        },
         {
            "id": 49,
            "item_name": "Japanese demon art face Skull devil oni harajuku aesthetic T-Shirt",
            "price": 15.95,
            "category": "Clothing",
            "description": "Harajuku lovers Oni what do you mean demon, minimal aesthetic streetwear style ninja, shinobi, ronin, yakuza. Minimalistic Stylish Otaku 80s 90s featuring a devil and evil mask hunter and Nippon style. halloween, thanksgiving, birthday, christmas Minimalist Japanese Kanji graphic tee, steamwave for otaku, anime nerd manga geek fan, japanese art culture weeaboo, vaporwave pastel goth punk, soft grunge, urban streetwear street style, feelings of chaos and conflict",
            "quantity": 30,
            "preview_imageURL": "https://m.media-amazon.com/images/I/A13usaonutL._CLa%7C2140%2C2000%7C81HMythsBbL.png%7C0%2C0%2C2140%2C2000%2B0.0%2C0.0%2C2140.0%2C2000.0_AC_UX679_.png",
            "sellerId": 4,
        },
        {
            "id": 50,
            "item_name": "Trippy Square Pants Long Sleeve Graphic Sweatshirt | Unisex, Up to 4XL",
            "price": 23.99,
            "category": "Clothing",
            "description": "Printed front and back with a rich vibrant design, this long sleeve sweater features a relaxed fit, straight stitched hems, ribbed crew neck and cuffs.",
            "quantity": 30,
            "preview_imageURL": "https://i5.walmartimages.com/asr/b6c1c2d8-1c3b-43d6-8a09-a91edd89a61c.e744f72f2247a34a96558e2e4282fd6f.jpeg?odnHeight=2000&odnWidth=2000&odnBg=ffffff",
            "sellerId": 5,
        },
         {
            "id": 51,
            "item_name": "OP Pirate Anime Wanted Posters",
            "price": 10.99,
            "category": "Home Decor",
            "description": "New Edition, 28.5cm×19.5cm, Luffy 1.5 Billion, Pack of 24",
            "quantity": 5,
            "preview_imageURL": "https://m.media-amazon.com/images/I/615ovA8lqCL._AC_UF894,1000_QL80_.jpg",
            "sellerId": 7,
        },
        {
            "id": 52,
            "item_name": "GAVIA Baby Skull Candle Set",
            "price": 5.99,
            "category": "Home Decor",
            "description": "GAVIA Baby Skull Candle Set - Scented - Gothic Decor - Witchy Room Decor - Goth Bedroom Decor - Skull Decor - Horror Decor - Spooky Home Decor - Gothic Home Decor - Witch Decor - Halloween Home Decor",
            "quantity": 6,
            "preview_imageURL": "https://m.media-amazon.com/images/I/81aj17oH5fL.__AC_SY445_SX342_QL70_FMwebp_.jpg",
            "sellerId": 5,
        },
         {
            "id": 53,
            "item_name": "Black skull lamp",
            "price": 39.99,
            "category": "Home Decor",
            "description": "This die-cut goth table lamp will enhance your gothic decor for bedroom with its sturdy construction and smooth finishing",
            "quantity": 10,
            "preview_imageURL": "https://m.media-amazon.com/images/I/717IYaih2PL.jpg",
            "sellerId": 1,
        },
         {
            "id": 54,
            "item_name": "Pink Sakura Plush Pillow",
            "price": 28.99,
            "category": "Home Decor",
            "description": "Welcome to our enchanting 45cm Pink Sakura Plush Pillow! This delightful pillow is adorned with adorable kawaii flowers, bringing a touch of whimsy and charm to any space. Its lifelike softness and plush texture make it a perfect companion for relaxation and comfort.",
            "quantity": 15,
            "preview_imageURL": "https://i.etsystatic.com/43642340/r/il/bedfac/5019666540/il_1588xN.5019666540_9g3o.jpg",
            "sellerId": 2,
        },
         {
            "id": 55,
            "item_name": "Led Gamer Neon Sign Lights Game Controller Neon Sign for Gamer Room Decor Dimmable Neon Lights Gaming Boy Gifts Room Decor",
            "price": 31.49,
            "category": "Home Decor",
            "description": "Led neon signs are made of high-quality copper wire, which has good electrical conductivity and can be used for a long time. the light is soft and will not hurt your hands when you touch it.",
            "quantity": 24,
            "preview_imageURL": "https://ae01.alicdn.com/kf/Sc1c1de4b33fd44c0826345b981b46524C/Led-Gamer-Neon-Sign-Lights-Game-Controller-Neon-Sign-for-Gamer-Room-Decor-Dimmable-Neon-Lights.jpg",
            "sellerId": 2,
        },
         {
            "id": 56,
            "item_name": "Faux Leather Spike Rivet Choker Punk Necklace Jewelry",
            "price": 2.48,
            "category": "Accessories",
            "description": "Faux leather choker, spike decor, cool and punk. It is a perfect ornament to give you a special look. Suitable for nightclubs, dance hall, parties, holiday, etc.",
            "quantity": 43,
            "preview_imageURL": "https://m.media-amazon.com/images/I/31gx0vc8CNL._AC_.jpg",
            "sellerId": 6,
        },
        {
            "id": 57,
            "item_name": "FAOYUDAWEI Skull Ring For Men",
            "price": 5.45,
            "category": "Accessories",
            "description": "Retro punk style, suit for vintage motorcycles biker, hip hop, rock and gothic fans. Unique and good workmanship skull ring design for Rock 'n 'roll fans, meticulously crafted in great detail, as well as good cosplay jewelry for halloween party.",
            "quantity": 33,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61FuwABGQxL._AC_UX679_.jpg",
            "sellerId": 6,
        },
         {
            "id": 58,
            "item_name": "Egirl Aesthetic Skull Chokers",
            "price": 3.26,
            "category": "Accessories",
            "description": "The skull pendant necklace is made of high-quality alloy material, which is durable and wear-resistant. it can be used for a long time.",
            "quantity": 35,
            "preview_imageURL": "https://ae01.alicdn.com/kf/Sd572d22180334eb9956d00392906cc98q.jpg_640x640Q90.jpg_.webp",
            "sellerId": 7,
        },
         {
            "id": 59,
            "item_name": "Fairy Grunge Aesthetic Belt",
            "price": 13.99,
            "category": "Accessories",
            "description": "Fairy Grunge Aesthetic Belts for Women Fairy Grunge Accessories Grunge Fairycore Jewelry",
            "quantity": 39,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61UcZLIGnkL._AC_UY1000_.jpg",
            "sellerId": 7,
        },
         {
            "id": 60,
            "item_name": "Black Skull and Awl Earring 925 Sterling Silver",
            "price": 61.95,
            "category": "Accessories",
            "description": "These pair of earrings is made out of 925 sterling silver with black plated metallic finish. Although an ideal accessory for a Halloween party, these also make a perfect addition to Gothic fashion.",
            "quantity": 45,
            "preview_imageURL": "https://www.gnoce.com/media/catalog/product/cache/a95ad56dd2a79ef00be2f8cdc9ab0431/6/1/6110f6fee2569png.png",
            "sellerId": 7,
        },
        {
            "id": 61,
            "item_name": "Fate Orders Warrior Girl Armor Anime Body Pillow Cover Extra Large Pillow Case",
            "price": 40.00,
            "category": "Waifu Body Pillows",
            "description": "Spice up your living space with our top grade Anime Character Theme Body Pillow Cover. So many amazing characters to choose from to decorate your room. Simply slip on Character Pillow Cover over any body pillow insert and enjoy the company of your favorite character.",
            "quantity": 1,
            "preview_imageURL": "https://i5.walmartimages.com/asr/f326f93f-546c-4941-a53b-3bb16b0a239d.fb52e6385c267667c95098e926f86526.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF",
            "sellerId": 5,
        },
         {
            "id": 62,
            "item_name": "Genshin Impact Body Pillow - Dakimakura Mona Sorceress And Bunny Girl ",
            "price": 48.99,
            "category": "Waifu Body Pillows",
            "description": "The additional support and comfort provided by the dakimakura will help you achieve high-quality sleep, resulting in a full-body rest.",
            "quantity": 8,
            "preview_imageURL": "https://k-minded.com/cdn/shop/products/9366b51a1f7c174fab9f1d03662bdba3_d53c9ee7-6823-4b76-8354-971f0c7a6b91.png?v=1658824036&width=1445",
            "sellerId": 5,
        },
         {
            "id": 63,
            "item_name": "The Quintessential Quintuplets Nakano Nino Body Pillow Cover Zipper Anime Body Pillow Cover",
            "price": 40.00,
            "category": "Waifu Body Pillows",
            "description": "Material Peach Skin. The Fabric has a Unique feeling; and a satin-like luster; High Printing Accuracy, Clear patterns, Good Abrasion Resistance, Easy to Clean and Care;",
            "quantity": 4,
            "preview_imageURL": "https://i.ebayimg.com/images/g/iqIAAOSwcX9j6z2G/s-l1200.jpg",
            "sellerId": 5,
        },
         {
            "id": 64,
            "item_name": "Genshin Impact Anime Dakimakura Hugging Body Pillow Case Beelzebul Keqing 150cm Hentai Dakis",
            "price": 6.63,
            "category": "Waifu Body Pillows",
            "description": "Peach skin, 2way, Short plush Hello friends, this item only has a pillowcase, not a pillow core. If you mind, please do not buy it! ! ! ",
            "quantity": 1,
            "preview_imageURL": "https://ae01.alicdn.com/kf/Sc14c3129b81246dc850d6776594ab768w.jpg_640x640Q90.jpg_.webp",
            "sellerId": 5,
        },
         {
            "id": 65,
            "item_name": "Acolor Zero Two Body Pillow Case Darling in The FRANXX Pillowcase Blanket Hugs Pillow Cover Manga Anime Cosplay Long Hugging Body Peach Skin",
            "price": 28.00,
            "category": "Waifu Body Pillows",
            "description": "The Decorative Pillow Cases Can Be Allowed For Both Hand Wash And Machine Wash By Cold Or Warm Water.(Do Not Bleach And Iron)",
            "quantity": 1,
            "preview_imageURL": "https://images-cdn.ubuy.co.in/633b0cfbab8332772a08f4e6-zero-two-body-pillow-case-darling-in-the.jpg",
            "sellerId": 5,
        },
         {
            "id": 66,
            "item_name": "Jujutsu Kaisen: Jujutsu Kaisen, Vol. 1",
            "price": 7.94,
            "category": "Books",
            "description": "First published in Japan in 2018 by Shueisha Inc., Tokyo -- Title page verso. To gain the power he needs to save his friend from a cursed spirit, Yuji Itadori swallows a piece of a demon, only to find himself caught in the midst of a horrific war of the supernatural!",
            "quantity": 24,
            "preview_imageURL": "https://i5.walmartimages.com/seo/Jujutsu-Kaisen-Jujutsu-Kaisen-Vol-1-Series-1-Paperback-9781974710027_6bee7e19-3dd4-44d5-bb89-6a6c8b38bf6b.8c40c502af450f9d46bb38f8b65510f5.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF",
            "sellerId": 2,
        },
         {
            "id": 67,
            "item_name": "Zombie Makeout Club Vol 1: DeathWish",
            "price": 10.99,
            "category": "Books",
            "description": "A rebellious high school student is brought back to life in a strange underground facility after commiting suicide. Now, she must piece together not only how and why she has been resurrected, but also confront the fragmented memories of her past and the horrors of the laboratory that want to send her back to the afterlife. This breakneck story illustrates a violent vision of life after death.",
            "quantity": 24,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51umfKp7ekL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg",
            "sellerId": 2,
        },
         {
            "id": 68,
            "item_name": "Black Butler, Vol. 1 (Black Butler, 1)",
            "price": 13.00,
            "category": "Books",
            "description": "Just a stone's throw from London lies the manor house of the illustrious Phantomhive earldom and its master, one Ciel Phantomhive. Earl Phantomhive is a giant in the world of commerce, Queen Victoria's faithful servant...and a slip of a twelve-year-old boy. Fortunately, his loyal butler, Sebastian, is ever at his side, ready to carry out the young master's wishes. And whether Sebastian is called to save a dinner party gone awry or probe the dark secrets of London's underbelly, there apparently is nothing Sebastian cannot do. In fact, one might even say Sebastian is too good to be true...or at least, too good to be human...",
            "quantity": 30,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51Wip-j7MlL._SX498_BO1,204,203,200_.jpg",
            "sellerId": 4,
        },
         {
            "id": 69,
            "item_name": "ETERNAL: ILya Kuvshinov Illustration Works",
            "price": 23.06,
            "category": "Books",
            "description": "After the success of Momentary, Ilya has gained popularity and has had some exhibitions and created commercial works. One of the most prestigious jobs Ilya was offered was as the character and visual designer for the anime The Wonderland, directed by Keiichi Hara; Crayon Shin-chan series and Ghost in the Shell: SAC_2045. This talented illustrator, who was influenced by many Japanese artists, now has 1.y million followers on Instagram, and is established as an influencer of other illustrators around the world.",
            "quantity": 24,
            "preview_imageURL": "https://m.media-amazon.com/images/I/41Rz0ZNjFBL._SX398_BO1,204,203,200_.jpg",
            "sellerId": 2,
        },
         {
            "id": 70,
            "item_name": "Kaiju Girl Caramelise, Vol. 1 (Kaiju Girl Caramelise, 1)",
            "price": 13.00,
            "category": "Books",
            "description": "Suffering from a rare, incurable illness that causes frightening changes to her body, loner Kuroe Akaishi spends her high school days avoiding all her classmates-especially class idol Arata Minami and his groupies. But when Arata starts making her heart skip a beat with irritating regularity, Kuroe discovers that her illness actually has a big-make that MONSTER-secret: Romance turns her into Love-zilla...literally!",
            "quantity": 29,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51Y4dieYGJL._SX351_BO1,204,203,200_.jpg",
            "sellerId": 7,
        },
        {
            "id": 71,
            "item_name": "Floodland",
            "price": 19.99,
            "category": "Music",
            "description": "Floodland is the second studio album by English gothic rock band the Sisters of Mercy. It was released on 16 November 1987, through Merciful Release internationally and distributed by WEA, with Elektra Records handling the United States release",
            "quantity": 1,
            "preview_imageURL": "https://upload.wikimedia.org/wikipedia/en/3/31/The_Sisters_of_Mercy_-_Floodland_cover_art.png",
            "sellerId": 6,
        },
        {
            "id": 72,
            "item_name": "Only Theatre of Pain",
            "price": 29.99,
            "category": "Music",
            "description": "Only Theatre of Pain is the debut studio album by the American rock band Christian Death, released on March 24, 1982, by the Frontier record label. It is considered by most critics to be the harbinger of the deathrock style of music, as well as being highly influential on the American gothic music scene.",
            "quantity": 6,
            "preview_imageURL": "https://upload.wikimedia.org/wikipedia/en/9/94/Christian_Death_-_Only_Theatre_Of_Pain.jpg",
            "sellerId": 3,
        },
         {
            "id": 73,
            "item_name": "Kessoku Band",
            "price": 22.99,
            "category": "Music",
            "description": "Kessoku Band is the debut studio album by Kessoku Band, a fictional musical group from the anime television series Bocchi the Rock!, released digitally on December 25, 2022, and physically on CD on December 28 by Aniplex.",
            "quantity": 24,
            "preview_imageURL": "https://upload.wikimedia.org/wikipedia/en/thumb/3/3e/Kessoku_Band_album_cover.jpg/220px-Kessoku_Band_album_cover.jpg",
            "sellerId": 3,
        },
           {
            "id": 74,
            "item_name": "μ's Best Album Best Live! collection II",
            "price": 12.99,
            "category": "Music",
            "description": "μ's Best Album Best Live! Collection II is a continuation from μ's Best Album Best Live! Collection, covering the next portion of μ's discography up till the end of the third sub-unit singles.",
            "quantity": 23,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61HDSN3msfL._UF1000,1000_QL80_.jpg",
            "sellerId": 7,
        },
        {
            "id": 75,
            "item_name": "TV Anime 'Attack on Titan Season 2' (Original Soundtrack)",
            "price": 13.99,
            "category": "Music",
            "description": "'Attack on Titan Season 2' (Original Soundtrack). 2014. Hiroyuki Sawano - Kill la Kill Original Soundtrack. Hiroyuki Sawano.",
            "quantity": 53,
            "preview_imageURL": "https://static.wikia.nocookie.net/shingekinokyojin/images/2/20/Season_2_Original_Soundtrack_Cover.jpg/revision/latest?cb=20170610005221",
            "sellerId": 3,
        },
          {
            "id": 76,
            "item_name": "CALEMBOU Anime Figure Yae Miko Figure 1/7 PVC Home Decoration Collectible Figurines for Fans",
            "price": 59.99,
            "category": "Figurines",
            "description": "Good choice for any fans. This is a great birthday or Christmas gift for your friends and family who love the Genshin game.",
            "quantity": 9,
            "preview_imageURL": "https://m.media-amazon.com/images/I/61gaX5cG5aL.jpg",
            "sellerId": 5,
        },
         {
            "id": 77,
            "item_name": "Honkai Impact 3Rd Series Anime Figure Raiden Mei Herrscher of Thunder 1/8 PVC Models Standard and Extended Versions Periphery Models Xmas Gift 25cm",
            "price": 85.98,
            "category": "Figurines",
            "description": "This item is refined hand-tailored & fully customized. Exquisite face and costume carving, attractive look, lifelike pose inspire your imagination. The props are also highly simulated and vivid. The whole part is further polished including skin texture, clothes drape, color and luster, stable base.",
            "quantity": 7,
            "preview_imageURL": "https://m.media-amazon.com/images/I/51qJh40uGUL.jpg",
            "sellerId": 5,
        },
        {
            "id": 78,
            "item_name": "25cm Japanese Anime One Piece Anime Figure Action Figure Doll Fight Roronoa Zoro Action Figure model Toy",
            "price": 15.98,
            "category": "Figurines",
            "description": "Action Figure |Material: High Quality PVC, Eco-friendly & Non-toxic BTS related",
            "quantity": 23,
            "preview_imageURL": "https://m.media-amazon.com/images/I/41bRjDAzxtL._AC_UF1000,1000_QL80_.jpg",
            "sellerId": 7,
        },
         {
            "id": 79,
            "item_name": "TAMASHII NATIONS Son Goku Dragon Ball Z, Bandai Imagination Works , Black",
            "price": 54.98,
            "category": "Figurines",
            "description": "Bringing two dimensional characters into vivid three dimension life, using the large format 1/9 scale to achieve rich, fine detail and faithfully detailed coloring for the ultimate in visual appearance.",
            "quantity": 26,
            "preview_imageURL": "https://m.media-amazon.com/images/I/81Qo1uqByfL.jpg",
            "sellerId": 4,
        },
        {
            "id": 80,
            "item_name": "Banpresto BLEACH Solid And Souls Ichigo Kurosaki Figure",
            "price": 29.90,
            "category": "Figurines",
            "description": "Ichigo is ready to defend your figure shelves from hollows! Add your favorite Soul Reaper to your BLEACH collection with this figure of Ichigo Kurosaki, who's depicted with a serious expression and ready to fight!",
            "quantity": 26,
            "preview_imageURL": "https://cdn.media.amplience.net/s/hottopic/19311492_hi",
            "sellerId": 4,
        },



    ]

    for product in products:
        each_product = Product(**product)
        print(each_product)
        db.session.add(each_product)
        db.session.commit()
    return products


# Uses a raw SQL query to TRUNCATE or DELETE the products table. SQLAlchemy doesn't
# have a built in function to do this. With postgres in production TRUNCATE
# removes all the data from the table, and RESET IDENTITY resets the auto
# incrementing primary key, CASCADE deletes any dependent entities.  With
# sqlite3 in development you need to instead use DELETE to remove all data and
# it will reset the primary keys for you as well.
def undo_products():
    if environment == "production":
        db.session.execute(
            f"TRUNCATE table {SCHEMA}.products RESTART IDENTITY CASCADE;"
        )
    else:
        db.session.execute(text("DELETE FROM products"))

    db.session.commit()
